[package]
name = "stump"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shellexpand = "2.1.0"
walkdir = "2.3.2"
ansi_term = "0.12.1"
clap = "2.33.3"